apiVersion: v1
kind: ReplicaSet
metadata: 
  name: nginx
  # this are replica set lables
  labels: 
    purpose: rs-demo
    project: roboshop
spec:
  replicas: 3
  selector:
  #these labels are used to select pods
    mathLabels: 
      purpose: rs-demo
      project: roboshop
      #pod defination
  template:
    metadata:
    labes:
      purpose: rs-demo
      project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx

        